export enum SeriesAction {
    CREATE_SERIES = 'CREATE_SERIES',
    UPDATE_SERIES = 'UPDATE_SERIES',
    INCREASE_COUNT = 'INCREASE_COUNT',
    DECREASE_COUNT = 'DECREASE_COUNT',
    DELETE_SERIES = 'DELETE_SERIES'
}
